### PR TITLE
Remove the `CanStreamData` RPC

### LINKED ISSUE #74: Remove gRPC method `CanStreamData`
### What's needed?

Removal of this superflous method. The same information can be obtained by checking if the `StreamComponentData` method returns an error or not.

### Proposed solution

Remove `CanStreamData` method.

### Use cases

_No response_

### Alternatives and workarounds

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tiyash-basu-frequenz**
It can be checked by calling the `StreamComponentData` method, and checking if the response is an error or not.

### CODE REVIEW

**Comment by tiyash-basu-frequenz** [comment]
Marking it as blocked for now until we finalise the release plan for v0.15.2.

**Comment by llucax** [comment]
Unblocking as v0.15.2 was released :tada:

**Review by llucax — COMMENTED** [review]
LGTM

**Review by llucax — DISMISSED** [review]

**Comment by tiyash-basu-frequenz** [comment]
Rebased on v0.x.x to resolve conflicts.
Ready for another look.

**Review by matthias-wende-frequenz — APPROVED** [review]

**Review by llucax — APPROVED** [review]

**Review by thomas-nicolai-frequenz — COMMENTED** [review]
Looks good from my side.

**Pull request merged**
