### PR TITLE
ci: Test also Python 3.11

### PR DESCRIPTION
**Pull request by leandro-lucarella-frequenz**
We are very close to the release of Python 3.11 so it's a good idea to start testing aginst it too.

### CODE REVIEW

**Comment by leandro-lucarella-frequenz** [comment]
Not working, and it is not high prio, so I will not get into it for now...

**Comment by tiyash-basu-frequenz** [comment]
@leandro-lucarella-frequenz Is there any plan to work on this in the coming days? If not, I'd suggest closing this, as this is getting stale.

**Comment by leandro-lucarella-frequenz** [comment]
It should be working in Python 3.11 since we are testing that with the SDK, I'll have a quick look to see if we can enable tests with Python 3.11 final here too.

**Comment by leandro-lucarella-frequenz** [comment]
All good now, thanks for the reminder @tiyash-basu-frequenz !

**Review by tiyash-basu-frequenz — DISMISSED** [review]
LGTM

**Comment by leandro-lucarella-frequenz** [comment]
Rebased on the current base branch and enabled auto-merge. So please re-approve when you can.

**Review by tiyash-basu-frequenz — APPROVED** [review]
LGTM

**Pull request merged**
