### PR TITLE
Clear release notes

### PR DESCRIPTION
**Pull request by tiyash-basu-frequenz**

### CODE REVIEW

**Review by leandro-lucarella-frequenz — APPROVED** [review]

**Comment by leandro-lucarella-frequenz** [comment]
Any reason to put this in a v0.12.1 milestone, is there a v0.12.1 coming?

**Comment by tiyash-basu-frequenz** [comment]
> Any reason to put this in a v0.12.1 milestone, is there a v0.12.1 coming?

Yes, we need to extend the API for sensors.

**Comment by leandro-lucarella-frequenz** [comment]
If it's not a bug fix, I would go with v0.13.0 though.

**Comment by tiyash-basu-frequenz** [comment]
> If it's not a bug fix, I would go with v0.13.0 though.

Fair enough.

**Pull request merged**
